title: 
Mon site d'entrainement
author: CatsLover71
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ceci est mon site de formation à l'utilisation de Github
  Je suis novice avec cette plateforme et donc je me forme
  afin de ne pas faire trop de bêtises.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
